#!/bin/sh
id -u _portzap > /dev/null 2>&1
if [ $? -ne 0 ]; then
    umask 707
    pw useradd -n _portzap \
               -c "portzap utility user" \
               -m \
               -s /sbin/nologin
    echo "The _portzap user and group has been created."
    echo "You might want to add user(s) to the _portzap group:"
    echo "pw groupmod -n _portzap -m <user>"
fi
